# See https://github.com/PolusAI/bfiocpp/blob/bc42abd41d44acd364c76a57bb2ce60168ba4258/README.md?plain=1#L16
c_stdlib_version:          # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]