{% set name = "bfiocpp" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }} 

source:
  url: https://github.com/PolusAI/{{ name }}/archive/{{ version }}.tar.gz
  sha256: bf4b6545094064ab8880dddd446a768cdd441ae8ae1f32e0f89e71451a802e8d
  patches:
    - windows_build.patch
    - cmake_osx_png.patch
build:
  skip: true  # [py2k or py<39]
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - git
    - nasm
    - ninja  # [win]
  host:
    - python
    - setuptools
    - pip
    - numpy
    - c-ares
    - openssl
    - bzip2
    - blosc
    - libcurl
    - libjpeg-turbo
    - libtiff
    - zstd
    - libpng
    - libwebp
    - lz4
    - xz
    - zlib
    - libprotobuf
    - benchmark
    - pybind11
    # this is header-only, so should be OK
    - nlohmann_json 3.10.5
    - libavif

  run:
    - python

test:
  imports:
    - bfiocpp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PolusAI/bfiocpp
  summary: Python library to read OME Tiff and OME NGFF files
  description: |
    The bfiocpp library provides a tensorstore based backend for bfio library to efficiently read
    OME Tiff and OME NGFF files
  license: Apache-2.0 AND MIT AND BSD-3-Clause AND BSD-2-Clause
  license_file: 
    - LICENSE
    - 3rd_party/absl/LICENSE
    - 3rd_party/half/LICENSE.txt
    - 3rd_party/re2/LICENSE
    - 3rd_party/riegeli/LICENSE
    - 3rd_party/tensorstore/LICENSE
  doc_url: https://bfio.readthedocs.io/en/latest/
  dev_url: https://github.com/PolusAI/bfiocpp

extra:
  recipe-maintainers:
    - sameeul
